/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.*;

import java.awt.event.*;
import java.util.*;
import javax.swing.*;


/**
 *
 * @author ed
 */
public class LoginView extends JPanel implements Observer {

    private Database db;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    public void setModel(Database db) {
        this.db = db;
        db.addObserver(this);
    }

    public void setController(EventListener el) {
        bLogin.addActionListener((ActionListener) el);
    }

    public void update(Observable o, Object arg) {
    }

    public String getPfLoginPassword() {
        return pfLoginPassword.getText();
    }

    public String getLoginUsername() {
        String username = this.tfLoginUsername.getText();
        if (!username.isEmpty()) {
            return username;
        } else {
            return null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoginUsername = new javax.swing.JLabel();
        tfLoginUsername = new javax.swing.JTextField();
        lblLoginPassword = new javax.swing.JLabel();
        pfLoginPassword = new javax.swing.JPasswordField();
        bLogin = new javax.swing.JButton();

        setName("Login"); // NOI18N

        lblLoginUsername.setText("Username");
        lblLoginUsername.setToolTipText("");

        lblLoginPassword.setText("Password");

        bLogin.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLoginPassword)
                    .addComponent(lblLoginUsername)
                    .addComponent(tfLoginUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(pfLoginPassword)
                    .addComponent(bLogin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLoginPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pfLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bLogin)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel lblLoginPassword;
    private javax.swing.JLabel lblLoginUsername;
    private javax.swing.JPasswordField pfLoginPassword;
    private javax.swing.JTextField tfLoginUsername;
    // End of variables declaration//GEN-END:variables
}
