package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.EventListener;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import model.*;

/**
 *
 * @author ed
 */
public class TransactionsView extends JPanel implements Observer {

    private UserList db;
    DefaultTableModel expenseModel;
    DefaultTableModel incomeModel;
    DefaultTableModel transferModel;

    /**
     * Creates new form TransactionsView
     */
    public TransactionsView() {
        // tables data placeholder  
        Object[][] data = {};

        // expense table headers
        String[] tableColumnNames = {"Description", "Amount", "Date", "Source account", "Destination account", "Category"};
        
        // expense table model
        expenseModel = new DefaultTableModel(data, tableColumnNames);

        // income table model
        incomeModel = new DefaultTableModel(data, tableColumnNames);

        // transfer table model
        transferModel = new DefaultTableModel(data, tableColumnNames);

        initComponents();

        // set text field to current date
        ftfTransactionDate.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));

    }

    public void setModel(UserList db) {
        this.db = db;
        db.addObserver(this);
    }

    public void setController(EventListener el) {
    }

    public void update(Observable o, Object arg) {
        System.out.println("Transaction view: updated");
        // clear the tables
        expenseModel.setRowCount(0); 
        incomeModel.setRowCount(0);
        transferModel.setRowCount(0);
        
        // if loggedIn populate the table with user data
        if (db.getLoggedInUser() != null) {
            db.getLoggedInUser().getTransactions().forEach(tra -> {
                switch (tra.getType()) {
                    case WITHDRAWAL -> expenseModel.addRow(new Object[]{tra.getDescription(), tra.getAmount(), tra.getSourceAccount().getName(), tra.getDestinationAccount().getName(), tra.getDescription(), tra.getCategory()});

                    case DEPOSIT -> incomeModel.addRow(new Object[]{tra.getDescription(), tra.getAmount(), tra.getSourceAccount().getName(), tra.getDestinationAccount().getName(), tra.getDescription(), tra.getCategory()});
                        
                    case TRANSFER -> transferModel.addRow(new Object[]{tra.getDescription(), tra.getAmount(), tra.getSourceAccount().getName(), tra.getDestinationAccount().getName(), tra.getDescription(), tra.getCategory()});

                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        tpTransactions = new javax.swing.JTabbedPane();
        expensePane = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expenseTable = new javax.swing.JTable();
        incomePane = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();
        transferPane = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        transferTable = new javax.swing.JTable();
        newTransactionPane = new javax.swing.JPanel();
        bTransactionSubmit = new javax.swing.JButton();
        tfTransactionDescription = new javax.swing.JTextField();
        lblTransactionDescription = new javax.swing.JLabel();
        cbTransactionSourceAccount = new javax.swing.JComboBox<>();
        lblTransactionSourceAccount = new javax.swing.JLabel();
        lblTransactionDestinationAccount = new javax.swing.JLabel();
        cbTransactionDestinationAccount = new javax.swing.JComboBox<>();
        ftfTransactionDate = new javax.swing.JFormattedTextField();
        lblTransactionDate = new javax.swing.JLabel();
        lblTransactionAmount = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        lblTransactionCategory = new javax.swing.JLabel();
        cbTransactionCategory = new javax.swing.JComboBox<>();
        lblTransactionType = new javax.swing.JLabel();
        cbTransactionType = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setName("Transactions"); // NOI18N

        expensePane.setName(""); // NOI18N

        expenseTable.setModel(expenseModel);
        jScrollPane1.setViewportView(expenseTable);

        javax.swing.GroupLayout expensePaneLayout = new javax.swing.GroupLayout(expensePane);
        expensePane.setLayout(expensePaneLayout);
        expensePaneLayout.setHorizontalGroup(
            expensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        expensePaneLayout.setVerticalGroup(
            expensePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpTransactions.addTab("Expense", expensePane);

        incomeTable.setModel(incomeModel);
        jScrollPane2.setViewportView(incomeTable);

        javax.swing.GroupLayout incomePaneLayout = new javax.swing.GroupLayout(incomePane);
        incomePane.setLayout(incomePaneLayout);
        incomePaneLayout.setHorizontalGroup(
            incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        incomePaneLayout.setVerticalGroup(
            incomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpTransactions.addTab("Income", incomePane);

        transferTable.setModel(transferModel);
        jScrollPane3.setViewportView(transferTable);

        javax.swing.GroupLayout transferPaneLayout = new javax.swing.GroupLayout(transferPane);
        transferPane.setLayout(transferPaneLayout);
        transferPaneLayout.setHorizontalGroup(
            transferPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
        );
        transferPaneLayout.setVerticalGroup(
            transferPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpTransactions.addTab("Transfer", transferPane);

        jSplitPane1.setRightComponent(tpTransactions);

        bTransactionSubmit.setText("Submit");

        lblTransactionDescription.setText("Description");

        cbTransactionSourceAccount.setEditable(true);
        cbTransactionSourceAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTransactionSourceAccount.setText("Source account");

        lblTransactionDestinationAccount.setText("Destination account");

        cbTransactionDestinationAccount.setEditable(true);
        cbTransactionDestinationAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ftfTransactionDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftfTransactionDate.setToolTipText("Format: 6 Dec 2021");

        lblTransactionDate.setText("Date");

        lblTransactionAmount.setText("Amount");

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        lblTransactionCategory.setText("Category");

        cbTransactionCategory.setEditable(true);
        cbTransactionCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTransactionType.setText("Type");

        cbTransactionType.setModel(new javax.swing.DefaultComboBoxModel<>(TransactionType.getTransactionTypes()));

        jLabel1.setText("€");

        javax.swing.GroupLayout newTransactionPaneLayout = new javax.swing.GroupLayout(newTransactionPane);
        newTransactionPane.setLayout(newTransactionPaneLayout);
        newTransactionPaneLayout.setHorizontalGroup(
            newTransactionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newTransactionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newTransactionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newTransactionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bTransactionSubmit)
                        .addGroup(newTransactionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTransactionDescription)
                            .addComponent(tfTransactionDescription)
                            .addComponent(cbTransactionSourceAccount, 0, 160, Short.MAX_VALUE)
                            .addComponent(lblTransactionSourceAccount)
                            .addComponent(lblTransactionDestinationAccount)
                            .addComponent(cbTransactionDestinationAccount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTransactionDate)
                            .addComponent(ftfTransactionDate)
                            .addComponent(lblTransactionAmount)
                            .addComponent(lblTransactionCategory)
                            .addComponent(cbTransactionCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblTransactionType)
                    .addComponent(cbTransactionType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newTransactionPaneLayout.createSequentialGroup()
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        newTransactionPaneLayout.setVerticalGroup(
            newTransactionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newTransactionPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransactionAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newTransactionPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lblTransactionSourceAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTransactionSourceAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(lblTransactionDestinationAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTransactionDestinationAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTransactionDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftfTransactionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTransactionType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTransactionCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTransactionCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTransactionDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTransactionDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bTransactionSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(newTransactionPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bTransactionSubmit;
    private javax.swing.JComboBox<String> cbTransactionCategory;
    private javax.swing.JComboBox<String> cbTransactionDestinationAccount;
    private javax.swing.JComboBox<String> cbTransactionSourceAccount;
    private javax.swing.JComboBox<String> cbTransactionType;
    private javax.swing.JPanel expensePane;
    private javax.swing.JTable expenseTable;
    private javax.swing.JFormattedTextField ftfTransactionDate;
    private javax.swing.JPanel incomePane;
    private javax.swing.JTable incomeTable;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblTransactionAmount;
    private javax.swing.JLabel lblTransactionCategory;
    private javax.swing.JLabel lblTransactionDate;
    private javax.swing.JLabel lblTransactionDescription;
    private javax.swing.JLabel lblTransactionDestinationAccount;
    private javax.swing.JLabel lblTransactionSourceAccount;
    private javax.swing.JLabel lblTransactionType;
    private javax.swing.JPanel newTransactionPane;
    private javax.swing.JTextField tfTransactionDescription;
    private javax.swing.JTabbedPane tpTransactions;
    private javax.swing.JPanel transferPane;
    private javax.swing.JTable transferTable;
    // End of variables declaration//GEN-END:variables
}
