@startuml
!theme plain
skinparam classAttributeIconSize 0
Class UserList {
- users : ArrayList<User>
- loggedInUser : User 
__
+ ArrayList<User> getUsers()
+ User getUserByUsername(String username)
+ Boolean usernameExists(String username)
..
+ void registerUser(String username, String email, String password, String bankName, String defaultBalance, String savingsBalance)
+ Boolean loginUser(String username, String password)
..
+ User getLoggedInUser()
+ void setLoggedInUser(User user)
..
+ void update(Observable o, Object arg)
..
+ void instantiateDummyData()
}
@enduml
