@startuml
!theme plain
skinparam classAttributeIconSize 0
Class User {
- id : UUID
- username : String
- email : String
- password : String
- networth : String
- accounts : ArrayList<Account> 
- transactions : ArrayList<Transaction> 
__
+ String getId()
+ String getUsername()
+ String getEmail()
+ String getPassword()
+ String getNetWorth()
..
+ void addTransaction(Transaction transaction)
+ ArrayList<Transaction> getTransactions()
..
+ void addAccount(Account account)
+ ArrayList<Account> getAccounts()
..
+ Sring[] getAccountsNames()
+ Account getAccountById(String id)
+ Account getAccountByName(String name)
..
+ ArrayList getAllCategories()
+ String getCategoryTotalByCategory(String category)
..
+ String toString()
}
@enduml
