@startuml 
!theme plain
start
:Register button clicked;
if (usernameExists) then (no)
  :Create
  User;
  :Create
  Accounts;
  :Create
  Transactions;
  :Success user created; 
  stop
else (yes) 
  :Error username
   already exists;
  end
@enduml